/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author ADMIN
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTop1Right = new javax.swing.JPanel();
        jlArrage = new javax.swing.JLabel();
        cbArrange = new lib2.ComboBoxSuggestion();
        btnArrange = new lib2.Button();
        jlArrage1 = new javax.swing.JLabel();
        cbArrange1 = new lib2.ComboBoxSuggestion();
        btnArrange1 = new lib2.Button();

        jpTop1Right.setBackground(new java.awt.Color(255, 255, 255));

        jlArrage.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jlArrage.setText("Sắp xếp theo :");

        cbArrange.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Họ tên", "Doanh thu cao nhất", "Doanh thu thấp nhất" }));

        btnArrange.setBackground(new java.awt.Color(135, 206, 235));
        btnArrange.setForeground(new java.awt.Color(255, 255, 255));
        btnArrange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/arrange24.png"))); // NOI18N
        btnArrange.setText("Sắp xếp");
        btnArrange.setToolTipText("");
        btnArrange.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jpTop1RightLayout = new javax.swing.GroupLayout(jpTop1Right);
        jpTop1Right.setLayout(jpTop1RightLayout);
        jpTop1RightLayout.setHorizontalGroup(
            jpTop1RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTop1RightLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jlArrage)
                .addGap(18, 18, 18)
                .addComponent(cbArrange, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnArrange, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jpTop1RightLayout.setVerticalGroup(
            jpTop1RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTop1RightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTop1RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpTop1RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbArrange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlArrage))
                    .addComponent(btnArrange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jlArrage1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jlArrage1.setText("Sắp xếp theo :");

        cbArrange1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Họ tên", "Doanh thu cao nhất", "Doanh thu thấp nhất" }));

        btnArrange1.setBackground(new java.awt.Color(135, 206, 235));
        btnArrange1.setForeground(new java.awt.Color(255, 255, 255));
        btnArrange1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/arrange24.png"))); // NOI18N
        btnArrange1.setText("Sắp xếp");
        btnArrange1.setToolTipText("");
        btnArrange1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jpTop1Right, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addComponent(jlArrage1)
                    .addGap(18, 18, 18)
                    .addComponent(cbArrange1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnArrange1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(83, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jpTop1Right, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(133, 133, 133)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbArrange1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlArrage1))
                        .addComponent(btnArrange1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(133, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lib2.Button btnArrange;
    private lib2.Button btnArrange1;
    private lib2.ComboBoxSuggestion cbArrange;
    private lib2.ComboBoxSuggestion cbArrange1;
    private javax.swing.JLabel jlArrage;
    private javax.swing.JLabel jlArrage1;
    private javax.swing.JPanel jpTop1Right;
    // End of variables declaration//GEN-END:variables
}
